homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www/motion'
config:
hassio:
system_health:
http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.1
updater:
customizer:
  custom_ui: hosted
cloud: !include assistants/cloud.yaml
homekit: !include assistants/homekit.yaml
ios: !include notify/ios_config.yaml

discovery:
  ignore:
    - igd

# ########################################
# ###                GUI               ###
# ########################################
lovelace:
  mode: yaml
map:
frontend:
  javascript_version: latest
  themes: !include_dir_named themes

panel_custom: !include panels/panel_custom.yaml
panel_iframe: !include panels/panel_iframe.yaml

custom_updater:
  track:
    - cards
    - components
  # show_installable: true
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

# ########################################
# ###              ENTITIES             ###
# ########################################

media_player: !include entities/media_player.yaml
device_tracker: !include entities/device_tracker.yaml
zone: !include_dir_merge_list zones/

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
shopping_list:
notify: !include notify/notify.yaml

python_script:
 
tts:
  - platform: google

ffmpeg:

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'
  lovelace_gen_states: !secret lovelace_gen_states